global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  - prometheus.rules

scrape_configs:
  - job_name: prometheus
    static_configs:
    - targets: ['localhost:9090']
  - job_name: alertmanager
    static_configs:
    - targets: ['localhost:9093']
  - job_name: node
    file_sd_configs:
    - files: ['/etc/prometheus/node_exporter.json']
    relabel_configs:
    - source_labels: ['__address__']
      target_label: 'host'
      regex: '(.*):.*'
    - source_labels: ['__address__']
      target_label: 'instance'
      regex: '(.*):.*'
      replacement: '${1}:9100'
  - job_name: cadvisor
    file_sd_configs:
    - files: ['/etc/prometheus/cadvisor.json']
    relabel_configs:
    - source_labels: ['__address__']
      target_label: 'host'
      regex: '(.*):.*'
    - source_labels: ['__address__']
      target_label: 'instance'
      regex: '(.*):.*'
      replacement: '${1}:8080'
@SCRAPE_CONFIGS@

alerting:
  alertmanagers:
  - scheme: @ALERTMANAGER_SCHEME@
    static_configs:
    - targets:
      - "@ALERTMANAGER_URL@"
